import {Injectable} from "@angular/core";
import {HttpClient} from "@angular/common/http";
import {ProductsService} from "../products/products.service";
import {Product} from "./product.model";

@Injectable({providedIn: 'root'})
export class DataStorageService {


  constructor(
    private http: HttpClient,
    private productsService: ProductsService,
  ) {
  }

  private static composeFirebaseUrl(endpoint: string) {
    const firebaseUrl = 'https://chloopaki-shop.firebaseio.com/';
    const firebaseSuffix = '.json';
    return firebaseUrl + endpoint + firebaseSuffix;
  }

  storeProducts() {
    const products = this.productsService.getProducts();
    const url = DataStorageService.composeFirebaseUrl('products');
    this.http.put(url, products) // data sent with PUT (multi, overriding) is sent without ID's,
      // data sent by POST (single, appending) is stored with autogenerated ID
      .subscribe(response => {
        console.log(response);
      });
  }

  fetchRecipes() {
    const url = DataStorageService.composeFirebaseUrl('products');
    this.http
      .get<Product[]>(url).subscribe(response => {
      console.log(response);
      this.productsService.setProducts(response);
    })
  }
}
