import {Injectable} from "@angular/core";
import {HttpClient} from "@angular/common/http";
import {ProductsService} from "../products/products.service";
import {Product} from "./product.model";
import {CategoriesService} from "../categories/categories.service";
import {Category} from "./category.model";
import {Supplier} from "./supplier.model";
import {SuppliersService} from "../suppliers/suppliers.service";

@Injectable({providedIn: 'root'})
export class DataStorageService {

  private backendUrl = 'http://localhost:8888';

  constructor(
    private http: HttpClient,
    private productsService: ProductsService,
    private categoryService: CategoriesService,
    private suppliersService: SuppliersService,
  ) {
  }

  private static composeFirebaseUrl(endpoint: string) {
    const firebaseUrl = 'https://chloopaki-shop.firebaseio.com/';
    const firebaseSuffix = '.json';
    return firebaseUrl + endpoint + firebaseSuffix;
  }

  storeProducts() {
    const products = this.productsService.getProducts();
    const url = DataStorageService.composeFirebaseUrl('products');
    this.http.put(url, products) // data sent with PUT (multi, overriding) is sent without ID's,
      // data sent by POST (single, appending) is stored with autogenerated ID
      .subscribe(response => {
        //todo
        console.log(response);
      });
  }

  fetchAllProducts() {
    const url = this.backendUrl + '/products';
    this.getProducts(url);
  }

  fetchProductsByCategoryId(categoryId: number) {
    const url = `${this.backendUrl}/categories/${categoryId}/products`;
    this.getProducts(url);
  }

  fetchProductsBySupplierId(supplierId: number) {
    const url = `${this.backendUrl}/suppliers/${supplierId}/products`;
    this.getProducts(url);
  }

  private getProducts(url: string) {
    this.http
      .get<Product[]>(url).subscribe(response => {
      this.productsService.setProducts(response);
    });
  }

  fetchCategories() {
    const url = this.backendUrl + '/categories';
    this.http
      .get<Category[]>(url).subscribe(response => {
      this.categoryService.setCategories(response);
    })
  }

  fetchSuppliers() {
    const url = this.backendUrl + '/suppliers';
    this.http
      .get<Supplier[]>(url).subscribe(response => {
      this.suppliersService.setSuppliers(response);
    })
  }
}
